Added Poison Effect Upon leaving room's area
CompactMods/CompactMachines pull request #534
Opened 2022-07-23 12:49 UTC by RealMangorage

Added the Poison affect so that when players leave their room by somehow getting out of it and into the void of Compact Dimension itll do the following:

Give Them poison and Blindness
Teleports em back to the machine they last went into (if none then it just continues to poison them)

2022-07-23 15:17 UTC, Apceniy commented
But in 1.12 it teleports you out of the machine, not back into it

2022-07-23 20:44 UTC, robotgryphon requested changes

2022-07-23 20:44 UTC, robotgryphon commented on src/main/java/dev/compactmods/machines/wall/MachineVoidAir.java
> +    final public static DamageSource DAMAGE_SOURCE = new DamageSource("machinevoidair");
Consider underscores/prefix of mod id here

2022-07-23 20:44 UTC, robotgryphon commented on src/main/java/dev/compactmods/machines/wall/MachineVoidAir.java
> +                PlayerUtil.teleportPlayerBackToMachine((ServerLevel) pLevel, player);
1.12 teleported the player fully out of the machine, prefer that util method

2022-07-23 20:44 UTC, robotgryphon commented on src/main/java/dev/compactmods/machines/upgrade/ChunkloadUpgradeItem.java
> +        if (tab != CompactMachines.COMPACT_MACHINES_ITEMS) return;
Unrelated, please revert/open a new PR

2022-07-23 20:44 UTC, robotgryphon commented on src/datagen/java/dev/compactmods/machines/datagen/lang/EnglishLangGenerator.java
> +        add("death.attack." + MachineVoidAir.DAMAGE_SOURCE.msgId, "%1$s Died from Machine Void Air");
Would prefer to align with other death messages, ie "`player` failed to enter the void"

2022-07-23 21:00 UTC, RealMangorage commented
Ok I did I fixed em.

2022-07-25 09:10 UTC, robotgryphon requested changes
Looking much better; one more cleanup pass and it should be clear

2022-07-25 09:10 UTC, robotgryphon commented on src/main/java/dev/compactmods/machines/config/ServerConfig.java
> +
Needs moved to a new section, this is in the `commands` section. Also, prefer Java casing, `allowOutside`

2022-07-25 09:10 UTC, robotgryphon commented on src/main/java/dev/compactmods/machines/util/PlayerUtil.java
> +import net.minecraft.world.level.GameType;
Clean up imports

2022-07-25 09:10 UTC, robotgryphon commented on src/main/java/dev/compactmods/machines/util/PlayerUtil.java
> +
Evaluating if this is necessary; if the config option isn't an option list between tele back and tele out, this should probably just be removed. If kept, the non-existent history conditional block should fall into returning the player back to their spawn (`teleportPlayerToRespawnOrOverworld`)

2022-07-25 09:10 UTC, robotgryphon commented on src/main/java/dev/compactmods/machines/upgrade/RoomUpgradeItem.java
> +
Remove rogue spacing please

2022-07-25 09:10 UTC, robotgryphon commented on src/main/java/dev/compactmods/machines/upgrade/ChunkloadUpgradeItem.java
> +import dev.compactmods.machines.CompactMachines;
Remove unnecessary file changes, to reduce patch size

2022-07-25 10:12 UTC, robotgryphon approved these changes

2022-07-25 10:16 UTC, merged